# Site settings
title: Stefan DiBella | Customer Experience Consulting
email: your-email@example.com
description: >-
  Customer Experience Consulting services by Stefan DiBella. Practical CX solutions
  that scale with your business without unnecessary complexity.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social media profiles
linkedin_username: stefandibella
twitter_username: 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Permalink structure
permalink: /blog/:year/:month/:day/:title/
# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/